"""init_llmops_tables

Revision ID: d701153c3c5c
Revises: 
Create Date: 2026-05-18 14:20:37.119372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd701153c3c5c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('consumer_id', sa.Text(), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('success','failure','partial')", name='ck_batch_runs_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consumer_id', 'run_id', name='uq_batch_runs_consumer_run')
    )
    op.create_index('ix_batch_runs_consumer_started', 'batch_runs', ['consumer_id', 'started_at'], unique=False)
    op.create_index('ix_batch_runs_received', 'batch_runs', ['received_at'], unique=False)
    op.create_table('llm_models',
    sa.Column('model_id', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('host', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('digest', sa.Text(), nullable=True),
    sa.Column('source_modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('family', sa.Text(), nullable=True),
    sa.Column('parameter_size', sa.Text(), nullable=True),
    sa.Column('quantization', sa.Text(), nullable=True),
    sa.Column('format', sa.Text(), nullable=True),
    sa.Column('role_tags', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('owner', sa.Text(), nullable=True),
    sa.Column('adopted_at', sa.Date(), nullable=True),
    sa.Column('deprecated_at', sa.Date(), nullable=True),
    sa.Column('replaced_by', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("provider IN ('ollama','mlx','gguf')", name='ck_llm_models_provider'),
    sa.PrimaryKeyConstraint('model_id', 'provider', 'host', name='pk_llm_models')
    )
    op.create_index('ix_llm_models_active', 'llm_models', ['provider'], unique=False, postgresql_where=sa.text('deprecated_at IS NULL'))
    op.create_index('ix_llm_models_family', 'llm_models', ['family'], unique=False)
    op.create_table('llmops_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('google_sub', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_sub')
    )
    op.create_table('batch_run_stages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('batch_run_id', sa.BigInteger(), nullable=False),
    sa.Column('stage_order', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['batch_run_id'], ['batch_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_batch_run_stages_model', 'batch_run_stages', ['model'], unique=False)
    op.create_table('llmops_audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['llmops_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_llmops_audit_at', 'llmops_audit_log', ['at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_llmops_audit_at', table_name='llmops_audit_log')
    op.drop_table('llmops_audit_log')
    op.drop_index('ix_batch_run_stages_model', table_name='batch_run_stages')
    op.drop_table('batch_run_stages')
    op.drop_table('llmops_users')
    op.drop_index('ix_llm_models_family', table_name='llm_models')
    op.drop_index('ix_llm_models_active', table_name='llm_models', postgresql_where=sa.text('deprecated_at IS NULL'))
    op.drop_table('llm_models')
    op.drop_index('ix_batch_runs_received', table_name='batch_runs')
    op.drop_index('ix_batch_runs_consumer_started', table_name='batch_runs')
    op.drop_table('batch_runs')
    # ### end Alembic commands ###
